services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 60s  # Increased for S3 upload completion
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128

    # Override entrypoint to use our custom script
    entrypoint: ["/app/entrypoint.sh"]

    environment:
      - FRIGATE_RTSP_PASSWORD="password"
      
      # S3 Configuration (required for S3 mirroring)
      - S3_BUCKET=your-bucket-name
      - S3_ACCESS_KEY=your-access-key
      - S3_SECRET_KEY=your-secret-key
      
      # S3 Optional Configuration
      - S3_REGION=us-west-2                    # AWS region (default: us-east-1)
      - S3_PATH_PREFIX=frigate/snapshots       # S3 key prefix (default: none)
      - S3_ENDPOINT_URL=                       # For S3-compatible services (MinIO, Wasabi, etc.)
      
      # S3 Performance Tuning
      - S3_UPLOAD_THREADS=8                    # Parallel upload threads (default: 8)
      - S3_BATCH_SIZE=50                       # Events to process per batch (default: 50)
      - S3_STORAGE_CLASS=STANDARD_IA           # S3 storage class (default: STANDARD_IA)
      - S3_MAX_FAILED_RETRIES=3                # Max retries for failed uploads (default: 3)
      
      # Python optimizations for reliability
      - PYTHONUNBUFFERED=1                     # Ensure logs are flushed immediately
      - PYTHONDONTWRITEBYTECODE=1              # Prevent .pyc files

    volumes:
      - /Volumes/2024/frigate/media:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
      
      # Mount our S3 modules and patcher
      - ./s3.py:/app/s3.py:ro
      - ./s3_snapshot_mirror.py:/app/s3_snapshot_mirror.py:ro
      - ./s3_mirror_patcher.py:/app/s3_mirror_patcher.py:ro
      - ./s3_mirror_entrypoint.sh:/app/entrypoint.sh:ro

    ports:
      - "8971:8971"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    
    # Health check to ensure Frigate is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    
    # Resource limits for stability
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 2G